default:
  service:
    name: sr-nodejs
    port: 4000
    databases:
      main:
        dialect: mysql
        host: movistardb.cjcmv3tc2pyq.us-east-1.rds.amazonaws.com
        port: 3306
        dbName: interview_db
        user: interview
        password: interview123
  metadata:
    enviroment: local
